package dummy.events;

dialect "mvel"

import java.util.Date
import java.util.LinkedList

global org.slf4j.Logger logger

// --------------------------------------------------------------
declare StartEvent
  @role(event)
  name: String
  host: String
end

// --------------------------------------------------------------
declare CpuPeak
  @role(event)
  host: String
  value: int
end

// --------------------------------------------------------------
rule "CPU issue"
when
  $peak: CpuPeak($host:host, value > 90)
  LinkedList(size == 0) from collect (
    StartEvent(host==$host, this before[5s] $peak)
  )
then
  logger.info("very high CPU issue for host "+$host)
end

// --------------------------------------------------------------
rule "NO CPU issue"
when
  $peak: CpuPeak($host:host, value > 90)
  StartEvent(host==$host, this before[0,5s] $peak)  
then
  logger.info("THIS IS not a high CPU issue for host "+$host)
end

