package dummy.maps

import dummy.GenericEvent
import dummy.Event
import dummy.EventDecision

dialect "mvel"

global org.slf4j.Logger logger


// ------------------------------------------------------------------

rule "truc"
when
  $event: GenericEvent(kind=="truc")
then
  logger.info("truc rule fired up")
  insert(new EventDecision("truc rule fired up"))
end


// ------------------------------------------------------------------
// ne pas utiliser la notation props.x ou si et seulement si toutes
// les instances dispose de la propriété x (ce qui est le cas ici!)

rule "machin with x"
when
  //$event: GenericEvent(kind=="machin", props["x"] =="1")
  $event: GenericEvent(kind=="machin", props.x == "1")
then
  logger.info("machin with x fired up : "+$event)
  insert(new EventDecision("machin with x fired up : "+$event))
end


// ------------------------------------------------------------------
// ne pas utiliser la notation props.y ou si et seulement si toutes
// les instances dispose de la propriété y (ce qui n'est pas le cas ici)

rule "machin with y"
when
  $event: GenericEvent(kind=="machin", props["y"] =="3")
  //$event: GenericEvent(kind=="machin", props.y == "3")
then
  logger.info("machin with y fired up : "+$event)
  insert(new EventDecision("machin with y fired up : "+$event))
end
